// canine_model.h  —  auto-generated by export_model.py
// Source: Master Threshold Classification Table (Thesis Table 2)
//
// Implements the 2-of-3 heat-stress rule directly from the validated thresholds.
// Heart rate is excluded per project design (not measured by ESP32 hardware).
//
// Features (must be supplied in this order):
//   body_temp        (deg C)
//   respiratory_rate (cycles/min)
//   ambient_temp     (deg C)

#pragma once
#include <Arduino.h>

// ── Thresholds (Master Threshold Classification Table) ───────────────────
static const float BODY_TEMP_HEAT_CUTOFF    = 39.5f;    // > this -> stressed
static const float RESP_RATE_HEAT_LOWER     = 29.0f;   // >= this -> stressed (no upper cap)
static const float AMBIENT_TEMP_HEAT_CUTOFF = 30.0f;  // > this -> stressed

// ── classify() ───────────────────────────────────────────────────────────
// Returns 1 = HEAT_STRESSED when >= 2 of 3 sensors are in the stressed zone.
// Returns 0 = NORMAL otherwise.
inline int classify(float body_temp, float resp_rate, float ambient_temp) {
  int stressed = 0;
  if (body_temp    >  BODY_TEMP_HEAT_CUTOFF)    stressed++;
  if (resp_rate    >= RESP_RATE_HEAT_LOWER)      stressed++;
  if (ambient_temp >  AMBIENT_TEMP_HEAT_CUTOFF)  stressed++;
  return (stressed >= 2) ? 1 : 0;
}
