/*
 * esp32_cooling_system.ino
 * -------------------------
 * Canine Heat Stroke Prevention System
 * Thesis: "IoT Monitoring of Vital Signs and Active Cooling for
 *          Canine Heat Stroke Prevention Using Binary Classification"
 *
 * ── Hardware ─────────────────────────────────────────────────────────────
 *   ESP32 development board
 *   DS18B20  waterproof probe  → body temperature (attached to collar)
 *   DHT22    sensor            → ambient temperature
 *   Respiratory sensor         → breath detection (piezo/flex + signal
 *                                conditioning board outputs one digital
 *                                RISING pulse per breath cycle)
 *   2-channel relay module     → Channel 1: Peltier module
 *                                Channel 2: Cooling fans
 *
 * ── Required Arduino libraries (install via Library Manager) ─────────────
 *   • OneWire            by Paul Stoffregen
 *   • DallasTemperature  by Miles Burton
 *   • DHT sensor library by Adafruit
 *
 * ── ML model file ────────────────────────────────────────────────────────
 *   Run  python export_model.py  in Python first, then copy the generated
 *   canine_model.h into THIS sketch's folder before compiling.
 *   That header exposes:  int classify(float body_temp,
 *                                      float resp_rate,
 *                                      float ambient_temp);
 *
 * ── Cooling state machine ────────────────────────────────────────────────
 *
 *   NORMAL  ──(2+ sensors stressed)──►  HEAT_STRESSED
 *                                            │
 *                                  (all readings return to normal)
 *                                            │
 *                                            ▼
 *                                   COOLDOWN_PELTIER  (60 s)
 *                                   Peltier ON, Fan ON
 *                                   (holds temperature steady)
 *                                            │
 *                                    (60 s elapsed)
 *                                            │
 *                                            ▼
 *                                    COOLDOWN_FAN  (120 s)
 *                                    Peltier OFF, Fan ON
 *                                    (retains cold air, prevents
 *                                     rapid temperature shift)
 *                                            │
 *                                   (120 s elapsed)
 *                                            │
 *                                            ▼
 *                                         NORMAL
 *
 *   From any cooldown state, if heat stress is detected again,
 *   the system immediately returns to HEAT_STRESSED.
 */

#include <OneWire.h>
#include <DallasTemperature.h>
#include <DHT.h>
#include "canine_model.h"   // generated by export_model.py

// ── Pin assignments ───────────────────────────────────────────────────────
#define DS18B20_PIN        4    // OneWire data (body temperature)
#define DHT_PIN            5    // DHT22 data   (ambient temperature)
#define DHT_TYPE           DHT22
#define RESP_SENSOR_PIN    35   // Digital input from respiratory sensor
                                // (GPIO35 is input-only on ESP32 — perfect here)
#define PELTIER_RELAY_PIN  25   // Relay channel 1: Peltier module
#define FAN_RELAY_PIN      26   // Relay channel 2: Cooling fans
#define STATUS_LED_PIN     2    // Built-in LED (ON = cooling active)

// ── Relay polarity ────────────────────────────────────────────────────────
// Most 5V relay modules are ACTIVE LOW: signal LOW energises the coil (ON).
// If your relay is active HIGH, swap the two lines below.
#define RELAY_ON    LOW
#define RELAY_OFF   HIGH

// ── Timing ───────────────────────────────────────────────────────────────
#define PELTIER_HOLD_MS   60000UL   // Peltier stays ON 60 s after readings normalise
#define FAN_HOLD_MS      120000UL   // Fan stays ON 120 s after Peltier turns off
#define SENSOR_SAMPLE_MS   2000UL   // Read all sensors every 2 s
#define RESP_WINDOW_MS    15000UL   // Count breaths over a 15 s window, extrapolate to /min

// ── Sensor objects ────────────────────────────────────────────────────────
OneWire           oneWire(DS18B20_PIN);
DallasTemperature bodyTempSensor(&oneWire);
DHT               dht(DHT_PIN, DHT_TYPE);

// ── Respiratory rate (interrupt-driven, non-blocking) ─────────────────────
volatile uint16_t  breathCount     = 0;
unsigned long      respWindowStart = 0;
float              latestRespRate  = 15.0f;   // initial default: mid-normal range

void IRAM_ATTR onBreath() {
  breathCount++;
}

// ── State machine ─────────────────────────────────────────────────────────
enum CoolingState : uint8_t {
  STATE_NORMAL,
  STATE_HEAT_STRESSED,
  STATE_COOLDOWN_PELTIER,
  STATE_COOLDOWN_FAN
};

CoolingState  coolingState   = STATE_NORMAL;
unsigned long cooldownTimer  = 0;
unsigned long lastSensorRead = 0;

// ── Relay helpers ─────────────────────────────────────────────────────────
inline void setPeltier(bool on) { digitalWrite(PELTIER_RELAY_PIN, on ? RELAY_ON : RELAY_OFF); }
inline void setFan    (bool on) { digitalWrite(FAN_RELAY_PIN,     on ? RELAY_ON : RELAY_OFF); }

void activateCooling() {
  setPeltier(true);
  setFan(true);
  digitalWrite(STATUS_LED_PIN, HIGH);
}

void deactivateCooling() {
  setPeltier(false);
  setFan(false);
  digitalWrite(STATUS_LED_PIN, LOW);
}

const char* stateName(CoolingState s) {
  switch (s) {
    case STATE_NORMAL:           return "NORMAL";
    case STATE_HEAT_STRESSED:    return "HEAT_STRESSED";
    case STATE_COOLDOWN_PELTIER: return "COOLDOWN_PELTIER";
    case STATE_COOLDOWN_FAN:     return "COOLDOWN_FAN";
    default:                     return "UNKNOWN";
  }
}

// ── Sensor reads ──────────────────────────────────────────────────────────
float readBodyTemp() {
  bodyTempSensor.requestTemperatures();
  float t = bodyTempSensor.getTempCByIndex(0);
  return (t == DEVICE_DISCONNECTED_C) ? -1.0f : t;
}

float readAmbientTemp() {
  float t = dht.readTemperature();
  return isnan(t) ? -1.0f : t;
}

// Called every loop; only recalculates when the 15 s window expires.
float getLatestRespRate() {
  unsigned long now = millis();
  if (now - respWindowStart >= RESP_WINDOW_MS) {
    noInterrupts();
    uint16_t count = breathCount;
    breathCount    = 0;
    interrupts();
    // Extrapolate count over the window to a per-minute rate
    latestRespRate = count * (60000.0f / (float)RESP_WINDOW_MS);
    respWindowStart = now;
  }
  return latestRespRate;
}

// ── State machine update ──────────────────────────────────────────────────
void updateCoolingState(int isStressed, unsigned long now) {
  CoolingState prev = coolingState;

  switch (coolingState) {

    case STATE_NORMAL:
      if (isStressed) {
        coolingState = STATE_HEAT_STRESSED;
        activateCooling();
      }
      break;

    case STATE_HEAT_STRESSED:
      if (!isStressed) {
        // Readings returned to normal — start the peltier hold timer.
        // Cooling hardware stays fully ON during this phase.
        coolingState = STATE_COOLDOWN_PELTIER;
        cooldownTimer = now;
      }
      break;

    case STATE_COOLDOWN_PELTIER:
      if (isStressed) {
        // Stress returned — abort cooldown, remain in full cooling mode.
        coolingState = STATE_HEAT_STRESSED;
        // Peltier + fan are already ON; no relay change needed.
      } else if (now - cooldownTimer >= PELTIER_HOLD_MS) {
        // 60 s elapsed — turn off Peltier, keep fan running to retain cold air.
        coolingState = STATE_COOLDOWN_FAN;
        cooldownTimer = now;
        setPeltier(false);
        // Fan stays ON (setFan remains true from activateCooling)
      }
      break;

    case STATE_COOLDOWN_FAN:
      if (isStressed) {
        // Stress detected during fan cooldown — restart full cooling.
        coolingState = STATE_HEAT_STRESSED;
        activateCooling();   // turns Peltier back on
      } else if (now - cooldownTimer >= FAN_HOLD_MS) {
        // 120 s elapsed — full cooldown complete, return to idle.
        coolingState = STATE_NORMAL;
        deactivateCooling();
      }
      break;
  }

  // Log state transitions to Serial Monitor
  if (coolingState != prev) {
    Serial.printf("\n[STATE CHANGE] %s  →  %s\n", stateName(prev), stateName(coolingState));
    switch (coolingState) {
      case STATE_HEAT_STRESSED:
        Serial.println("  ACTION : Peltier ON + Fans ON");
        break;
      case STATE_COOLDOWN_PELTIER:
        Serial.printf("  ACTION : Readings normal. Peltier+Fans ON for %lu s (hold temp).\n",
                      PELTIER_HOLD_MS / 1000UL);
        break;
      case STATE_COOLDOWN_FAN:
        Serial.printf("  ACTION : Peltier OFF. Fans ON for %lu s (retain cold, "
                      "prevent rapid temp shift).\n", FAN_HOLD_MS / 1000UL);
        break;
      case STATE_NORMAL:
        Serial.println("  ACTION : Cooldown complete. System idle. All cooling OFF.");
        break;
    }
  }
}

// ── Setup ─────────────────────────────────────────────────────────────────
void setup() {
  Serial.begin(115200);
  delay(500);

  Serial.println("\n========================================");
  Serial.println("  Canine Heat Stroke Prevention System  ");
  Serial.println("========================================");
  Serial.println("Initialising sensors and actuators...");

  pinMode(PELTIER_RELAY_PIN, OUTPUT);
  pinMode(FAN_RELAY_PIN,     OUTPUT);
  pinMode(STATUS_LED_PIN,    OUTPUT);
  deactivateCooling();   // safe default: everything OFF at boot

  bodyTempSensor.begin();
  dht.begin();

  // Attach interrupt for respiratory sensor (RISING edge = one breath detected)
  attachInterrupt(digitalPinToInterrupt(RESP_SENSOR_PIN), onBreath, RISING);
  respWindowStart = millis();

  Serial.println("Ready. Monitoring started.\n");
  Serial.println("body_temp(C)  resp_rate(bpm)  ambient(C)  state                result         cooldown");
  Serial.println("───────────────────────────────────────────────────────────────────────────────────────");
}

// ── Main loop ─────────────────────────────────────────────────────────────
void loop() {
  unsigned long now = millis();

  if (now - lastSensorRead >= SENSOR_SAMPLE_MS) {
    lastSensorRead = now;

    float bodyTemp    = readBodyTemp();
    float ambientTemp = readAmbientTemp();
    float respRate    = getLatestRespRate();

    // Sensor fault guard — skip this cycle if hardware reports invalid data
    if (bodyTemp < 0.0f || ambientTemp < 0.0f) {
      Serial.println("[WARN] Sensor read failed — check wiring. Skipping cycle.");
      return;
    }

    // ML inference (from canine_model.h)
    int prediction = classify(bodyTemp, respRate, ambientTemp);

    updateCoolingState(prediction, now);

    // ── Cooldown progress display ─────────────────────────────────────────
    unsigned long elapsed = 0;
    unsigned long target  = 0;
    if (coolingState == STATE_COOLDOWN_PELTIER || coolingState == STATE_COOLDOWN_FAN) {
      elapsed = (now - cooldownTimer) / 1000UL;
      target  = (coolingState == STATE_COOLDOWN_PELTIER) ? PELTIER_HOLD_MS / 1000UL
                                                         : FAN_HOLD_MS     / 1000UL;
    }

    // ── Serial monitor row ────────────────────────────────────────────────
    char cooldownBuf[20] = "-";
    if (target > 0) snprintf(cooldownBuf, sizeof(cooldownBuf), "%lus / %lus", elapsed, target);

    Serial.printf("%-13.2f %-15.1f %-11.2f %-20s %-14s %s\n",
                  bodyTemp,
                  respRate,
                  ambientTemp,
                  stateName(coolingState),
                  (prediction ? "HEAT_STRESSED" : "NORMAL"),
                  cooldownBuf);
  }
}
