"""
export_model.py
----------------
Trains the SVM model and exports it to an Arduino-compatible C++ header
(canine_model.h) that you place directly in your ESP32 sketch folder.

Workflow
--------
1.  python export_model.py          # creates canine_model.h
2.  Copy canine_model.h into your Arduino sketch folder (same folder as .ino)
3.  At the top of your .ino:  #include "canine_model.h"
4.  In your loop:             int result = classify(body_temp, resp_rate, ambient_temp);
                              // 1 = Heat Stressed  |  0 = Normal

Dependencies
------------
    pip install scikit-learn joblib pandas numpy
    pip install micromlgen          # optional — enables true SVM C++ export
                                    # without it, a rule-based fallback is written
"""

import argparse

import joblib
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from data_utils import (
    AMBIENT_TEMP_HEAT_CUTOFF,
    BODY_TEMP_HEAT_CUTOFF,
    RESP_RATE_HEAT_LOWER,
    generate_synthetic_dataset,
)
from svm_model import FEATURE_COLUMNS, build_svm_pipeline


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train_for_export(seed: int = 42):
    """Train a fixed-hyperparameter SVM and return the fitted pipeline."""
    df = generate_synthetic_dataset(seed=seed)
    X = df[FEATURE_COLUMNS]
    y = df["label"]
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=seed, stratify=y
    )
    pipeline = build_svm_pipeline(C=10, gamma=0.001)
    pipeline.fit(X_train, y_train)

    from sklearn.metrics import accuracy_score, recall_score
    y_pred = pipeline.predict(X_test)
    print(f"[INFO] Test accuracy: {accuracy_score(y_test, y_pred):.4f}  "
          f"Recall: {recall_score(y_test, y_pred):.4f}")
    return pipeline


# ---------------------------------------------------------------------------
# Export: micromlgen (true SVM C++ inference)
# ---------------------------------------------------------------------------

def export_with_micromlgen(pipeline, output_path: str) -> bool:
    """
    Exports a real SVM decision function to C++ using micromlgen.
    Returns True on success, False if micromlgen is not installed.
    """
    try:
        from micromlgen import port
    except ImportError:
        return False

    scaler = pipeline.named_steps["scaler"]
    svc    = pipeline.named_steps["svm"]

    svm_code = port(svc, classmap={0: "NORMAL", 1: "HEAT_STRESSED"})

    header = f"""\
// canine_model.h  —  auto-generated by export_model.py
// Do NOT edit by hand. Re-run export_model.py to regenerate.
//
// True SVM (RBF kernel) inference compiled for the ESP32.
// Features (must be supplied in this order):
//   body_temp        (deg C)
//   respiratory_rate (cycles/min)
//   ambient_temp     (deg C)

#pragma once
#include <Arduino.h>

// ── StandardScaler parameters (fitted on training data) ──────────────────
static const float SCALER_MEAN[3]  = {{
  {scaler.mean_[0]:.6f}f,   // body_temp mean
  {scaler.mean_[1]:.6f}f,   // respiratory_rate mean
  {scaler.mean_[2]:.6f}f    // ambient_temp mean
}};
static const float SCALER_SCALE[3] = {{
  {scaler.scale_[0]:.6f}f,  // body_temp std
  {scaler.scale_[1]:.6f}f,  // respiratory_rate std
  {scaler.scale_[2]:.6f}f   // ambient_temp std
}};

// ── SVM model (generated by micromlgen) ──────────────────────────────────
{svm_code}

// ── Public classify() function ───────────────────────────────────────────
// Returns 1 if the dog is heat-stressed, 0 if normal.
inline int classify(float body_temp, float resp_rate, float ambient_temp) {{
  float raw[3]    = {{ body_temp, resp_rate, ambient_temp }};
  float scaled[3];
  for (int i = 0; i < 3; i++) {{
    scaled[i] = (raw[i] - SCALER_MEAN[i]) / SCALER_SCALE[i];
  }}
  Eloquent::ML::Port::SVM svm;
  return svm.predict(scaled);   // 0 = NORMAL, 1 = HEAT_STRESSED
}}
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
    print(f"[micromlgen] Exported true SVM to '{output_path}'")
    return True


# ---------------------------------------------------------------------------
# Export: rule-based fallback (matches SVM decision boundary)
# ---------------------------------------------------------------------------

def export_threshold_fallback(output_path: str) -> None:
    """
    Writes the 2-of-3 threshold rule directly as a C++ classify() function.
    This is the primary export format — deterministic, always correct for any
    input range, and requires no SVM scaling or kernel computation on the ESP32.
    """
    header = f"""\
// canine_model.h  —  auto-generated by export_model.py
// Source: Master Threshold Classification Table (Thesis Table 2)
//
// Implements the 2-of-3 heat-stress rule directly from the validated thresholds.
// Heart rate is excluded per project design (not measured by ESP32 hardware).
//
// Features (must be supplied in this order):
//   body_temp        (deg C)
//   respiratory_rate (cycles/min)
//   ambient_temp     (deg C)

#pragma once
#include <Arduino.h>

// ── Thresholds (Master Threshold Classification Table) ───────────────────
static const float BODY_TEMP_HEAT_CUTOFF    = {BODY_TEMP_HEAT_CUTOFF}f;    // > this -> stressed
static const float RESP_RATE_HEAT_LOWER     = {float(RESP_RATE_HEAT_LOWER):.1f}f;   // >= this -> stressed (no upper cap)
static const float AMBIENT_TEMP_HEAT_CUTOFF = {float(AMBIENT_TEMP_HEAT_CUTOFF):.1f}f;  // > this -> stressed

// ── classify() ───────────────────────────────────────────────────────────
// Returns 1 = HEAT_STRESSED when >= 2 of 3 sensors are in the stressed zone.
// Returns 0 = NORMAL otherwise.
inline int classify(float body_temp, float resp_rate, float ambient_temp) {{
  int stressed = 0;
  if (body_temp    >  BODY_TEMP_HEAT_CUTOFF)    stressed++;
  if (resp_rate    >= RESP_RATE_HEAT_LOWER)      stressed++;
  if (ambient_temp >  AMBIENT_TEMP_HEAT_CUTOFF)  stressed++;
  return (stressed >= 2) ? 1 : 0;
}}
"""
    with open(output_path, "w") as f:
        f.write(header)
    print(f"[export] Rule-based classifier written to '{output_path}'")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Export trained SVM to Arduino C++ header")
    parser.add_argument("--output", type=str, default="canine_model.h",
                        help="Output header filename (place in your sketch folder)")
    parser.add_argument("--seed",   type=int, default=42)
    parser.add_argument("--save_model", type=str, default=None,
                        help="Optionally also save the sklearn pipeline (.joblib)")
    args = parser.parse_args()

    # Train the SVM pipeline (used for evaluation / accuracy reporting).
    # The SVM is NOT used for on-device inference — the rule-based classifier
    # is exported instead because it is always correct for any input range
    # and does not extrapolate incorrectly for out-of-distribution sensor readings.
    print("[INFO] Training SVM for evaluation...")
    pipeline = train_for_export(seed=args.seed)

    if args.save_model:
        joblib.dump(pipeline, args.save_model)
        print(f"[INFO] Sklearn pipeline saved to '{args.save_model}'")

    # Always export the rule-based classifier as canine_model.h
    export_threshold_fallback(args.output)

    print(f"\n{'='*60}")
    print(f"  Output file : {args.output}")
    print(f"  Next steps  :")
    print(f"    1. Copy '{args.output}' into your Arduino sketch folder")
    print(f"    2. Add at the top of your .ino:")
    print(f"         #include \"canine_model.h\"")
    print(f"    3. Call in your loop:")
    print(f"         int result = classify(body_temp, resp_rate, ambient_temp);")
    print(f"         // result: 1 = Heat Stressed, 0 = Normal")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
